export const exampleTheme = {
  paragraph: "text-base leading-relaxed text-gray-800",
  quote: "border-l-4 border-gray-300 pl-4 italic text-gray-600 my-4",
  heading: {
    h1: "text-2xl font-extrabold mt-6 mb-4",
    h2: "text-xl font-bold mt-5 mb-3",
    h3: "text-lg font-semibold mt-4 mb-2",
    subtitle: "text-lg text-gray-600 mb-4",
  },
  list: {
    nested: {
      listitem: "ml-6 list-disc",
    },
    ol: "list-decimal list-inside ml-4",
    ul: "list-disc list-inside ml-4",
    listitem: "ml-4",
    listitemChecked: "ml-4 line-through text-gray-500",
    listitemUnchecked: "ml-4",
  },
  alignment: {
    left: "text-left",
    center: "text-center",
    right: "text-right",
    justify: "text-justify",
  },
  hashtag: "text-indigo-600 font-medium",
  image: "w-full object-contain rounded-md my-4 shadow-sm",
  link: "text-blue-600 hover:underline",
  text: {
    bold: "font-bold",
    code: "bg-gray-100 text-sm font-mono px-1 py-0.5 rounded",
    italic: "italic",
    strikethrough: "line-through",
    subscript: "align-baseline text-xs",
    superscript: "align-baseline text-xs",
    underline: "underline",
    underlineStrikethrough: "underline line-through",
  },
  code: "bg-gray-900 text-white font-mono p-4 rounded text-sm overflow-auto",
  codeHighlight: {
    atrule: "text-purple-500",
    attr: "text-purple-500",
    boolean: "text-blue-500",
    builtin: "text-green-500",
    cdata: "text-gray-500 italic",
    char: "text-yellow-500",
    class: "text-green-600",
    "class-name": "text-green-600",
    comment: "text-gray-500 italic",
    constant: "text-blue-500",
    deleted: "text-red-500",
    doctype: "text-gray-500 italic",
    entity: "text-yellow-500",
    function: "text-green-500",
    important: "text-yellow-600 font-semibold",
    inserted: "text-green-500",
    keyword: "text-purple-600",
    namespace: "text-yellow-500",
    number: "text-blue-500",
    operator: "text-indigo-500",
    prolog: "text-gray-500 italic",
    property: "text-blue-500",
    punctuation: "text-gray-700",
    regex: "text-yellow-500",
    selector: "text-green-500",
    string: "text-green-500",
    symbol: "text-blue-500",
    tag: "text-red-500",
    url: "text-indigo-500 underline",
    variable: "text-yellow-500",
  },
};
